/* ERZEUGT von .farben_typen.py -- nicht von Hand aendern. */
window.TYPFARBEN = [
 {
  "key": "heute",
  "titel": "Heute (zum Vergleich)",
  "satz": "Vier Paletten von Hand: Chart hell, Chart dunkel, Chip hell, Chip dunkel.",
  "warum": "Gewachsen, nicht gerechnet -- jede Farbe einzeln gewaehlt.",
  "preis": "Ungleiche Gewichte und vier Farben, die praktisch dieselbe sind.",
  "cite": [
   {
    "key": "You",
    "label": "You",
    "fill": "#d35f73",
    "chip_light": "#d35f73",
    "chip_light_k": 3.24,
    "chip_dark": "#d76f82",
    "chip_dark_k": 4.79,
    "fill_dark": "#d76f82",
    "k_weiss": 3.71,
    "k_dunkel": 5.25
   },
   {
    "key": "Competition",
    "label": "Competition",
    "fill": "#dd7e3e",
    "chip_light": "#dd7e3e",
    "chip_light_k": 2.63,
    "chip_dark": "#de8c54",
    "chip_dark_k": 5.9,
    "fill_dark": "#de8c54",
    "k_weiss": 2.95,
    "k_dunkel": 6.46
   },
   {
    "key": "Editorial",
    "label": "Editorial",
    "fill": "#27a79b",
    "chip_light": "#27a79b",
    "chip_light_k": 2.62,
    "chip_dark": "#5cd7c8",
    "chip_dark_k": 8.88,
    "fill_dark": "#5cd7c8",
    "k_weiss": 2.96,
    "k_dunkel": 9.72
   },
   {
    "key": "UGC / Community",
    "label": "UGC / Community",
    "fill": "#34a1d1",
    "chip_light": "#34a1d1",
    "chip_light_k": 2.61,
    "chip_dark": "#62b4da",
    "chip_dark_k": 6.7,
    "fill_dark": "#62b4da",
    "k_weiss": 2.93,
    "k_dunkel": 7.33
   },
   {
    "key": "Institutional",
    "label": "Institutional",
    "fill": "#5e7eac",
    "chip_light": "#5e7eac",
    "chip_light_k": 3.63,
    "chip_dark": "#7693bb",
    "chip_dark_k": 4.92,
    "fill_dark": "#7693bb",
    "k_weiss": 4.15,
    "k_dunkel": 5.39
   },
   {
    "key": "Knowledge-Base",
    "label": "Knowledge-Base",
    "fill": "#797ad8",
    "chip_light": "#797ad8",
    "chip_light_k": 3.29,
    "chip_dark": "#8082db",
    "chip_dark_k": 4.53,
    "fill_dark": "#8082db",
    "k_weiss": 3.76,
    "k_dunkel": 4.97
   },
   {
    "key": "Brand Platforms",
    "label": "Brand Platforms",
    "fill": "#bc69c9",
    "chip_light": "#bc69c9",
    "chip_light_k": 3.07,
    "chip_dark": "#c377cf",
    "chip_dark_k": 5.07,
    "fill_dark": "#c377cf",
    "k_weiss": 3.5,
    "k_dunkel": 5.55
   }
  ],
  "url": [
   {
    "key": "homepage",
    "label": "Homepage",
    "familie": "Competition",
    "fill": "#c3753a",
    "chip_light": "#b45309",
    "chip_light_k": 4.39,
    "chip_dark": "#fbbf24",
    "chip_dark_k": 9.3,
    "fill_dark": "#fbbf24",
    "k_weiss": 3.54,
    "k_dunkel": 10.18
   },
   {
    "key": "product_service",
    "label": "Product / Service",
    "familie": "Competition",
    "fill": "#ce8662",
    "chip_light": "#c2683b",
    "chip_light_k": 3.5,
    "chip_dark": "#fdba74",
    "chip_dark_k": 9.2,
    "fill_dark": "#fdba74",
    "k_weiss": 2.91,
    "k_dunkel": 10.08
   },
   {
    "key": "marketplace",
    "label": "Marketplace",
    "familie": "Competition",
    "fill": "#ae7c58",
    "chip_light": "#9a5b2e",
    "chip_light_k": 4.71,
    "chip_dark": "#fcae6f",
    "chip_dark_k": 8.44,
    "fill_dark": "#fcae6f",
    "k_weiss": 3.61,
    "k_dunkel": 9.25
   },
   {
    "key": "company_info",
    "label": "Company Info",
    "familie": "Competition",
    "fill": "#b48139",
    "chip_light": "#a16207",
    "chip_light_k": 4.35,
    "chip_dark": "#facc15",
    "chip_dark_k": 10.14,
    "fill_dark": "#facc15",
    "k_weiss": 3.42,
    "k_dunkel": 11.1
   },
   {
    "key": "article",
    "label": "Article",
    "familie": "Editorial",
    "fill": "#369379",
    "chip_light": "#047857",
    "chip_light_k": 4.79,
    "chip_dark": "#6ee7b7",
    "chip_dark_k": 10.18,
    "fill_dark": "#6ee7b7",
    "k_weiss": 3.75,
    "k_dunkel": 11.15
   },
   {
    "key": "listicle",
    "label": "Listicle",
    "familie": "UGC / Community",
    "fill": "#3e90a6",
    "chip_light": "#0e7490",
    "chip_light_k": 4.7,
    "chip_dark": "#67e8f9",
    "chip_dark_k": 10.71,
    "fill_dark": "#67e8f9",
    "k_weiss": 3.66,
    "k_dunkel": 11.73
   },
   {
    "key": "guide",
    "label": "Guide",
    "familie": "Institutional",
    "fill": "#5182ef",
    "chip_light": "#2563eb",
    "chip_light_k": 4.52,
    "chip_dark": "#93c5fd",
    "chip_dark_k": 8.61,
    "fill_dark": "#93c5fd",
    "k_weiss": 3.63,
    "k_dunkel": 9.43
   },
   {
    "key": "comparison",
    "label": "Comparison",
    "familie": "Knowledge-Base",
    "fill": "#726bea",
    "chip_light": "#4f46e5",
    "chip_light_k": 5.44,
    "chip_dark": "#a5b4fc",
    "chip_dark_k": 7.79,
    "fill_dark": "#a5b4fc",
    "k_weiss": 4.19,
    "k_dunkel": 8.53
   },
   {
    "key": "review",
    "label": "Review",
    "familie": "Knowledge-Base",
    "fill": "#8a53e1",
    "chip_light": "#6d28d9",
    "chip_light_k": 6.06,
    "chip_dark": "#c4b5fd",
    "chip_dark_k": 8.41,
    "fill_dark": "#c4b5fd",
    "k_weiss": 4.77,
    "k_dunkel": 9.21
   },
   {
    "key": "documentation",
    "label": "Documentation",
    "familie": "Knowledge-Base",
    "fill": "#8a53e1",
    "chip_light": "#6d28d9",
    "chip_light_k": 6.06,
    "chip_dark": "#c4b5fd",
    "chip_dark_k": 8.41,
    "fill_dark": "#c4b5fd",
    "k_weiss": 4.77,
    "k_dunkel": 9.21
   },
   {
    "key": "video",
    "label": "Video",
    "familie": "Knowledge-Base",
    "fill": "#9661f1",
    "chip_light": "#7c3aed",
    "chip_light_k": 4.94,
    "chip_dark": "#c4b5fd",
    "chip_dark_k": 8.41,
    "fill_dark": "#c4b5fd",
    "k_weiss": 3.98,
    "k_dunkel": 9.21
   },
   {
    "key": "social_post",
    "label": "Social Post",
    "familie": "Knowledge-Base",
    "fill": "#a27df8",
    "chip_light": "#8b5cf6",
    "chip_light_k": 3.76,
    "chip_dark": "#ddd6fe",
    "chip_dark_k": 11.18,
    "fill_dark": "#ddd6fe",
    "k_weiss": 3.08,
    "k_dunkel": 12.24
   },
   {
    "key": "forum",
    "label": "Forum",
    "familie": "Brand Platforms",
    "fill": "#a95cee",
    "chip_light": "#9333ea",
    "chip_light_k": 4.66,
    "chip_dark": "#d8b4fe",
    "chip_dark_k": 8.78,
    "fill_dark": "#d8b4fe",
    "k_weiss": 3.85,
    "k_dunkel": 9.62
   },
   {
    "key": "directory",
    "label": "Directory",
    "familie": "Brand Platforms",
    "fill": "#b549bf",
    "chip_light": "#a21caf",
    "chip_light_k": 5.39,
    "chip_dark": "#f0abfc",
    "chip_dark_k": 8.82,
    "fill_dark": "#f0abfc",
    "k_weiss": 4.5,
    "k_dunkel": 9.66
   }
  ],
  "mass": {
   "L_min": 0.577,
   "L_max": 0.686,
   "L_spanne": 0.109,
   "C_min": 0.08,
   "C_max": 0.214,
   "C_spanne": 0.134,
   "hue_min_abstand": 0.0,
   "doppelte_farben": true
  }
 },
 {
  "key": "rad",
  "titel": "A -- Ein Rad",
  "satz": "Ein L, ein C, der Farbton ist die einzige Variable -- Linears Rechnung, unveraendert.",
  "warum": "Keine Flaeche draengt sich vor: alle 21 Farben sind gleich hell und gleich saturiert. Die 14 URL-Typen liegen in gleichen Schritten (26 Grad) auf dem Rad, in ihrer Familienreihenfolge.",
  "preis": "Die Zuordnung liest sich als Nachbarschaft auf dem Rad, nicht mehr als derselbe Farbton wie die Familie.",
  "cite": [
   {
    "key": "You",
    "label": "You",
    "fill": "#e47082",
    "chip_light": "#b7485c",
    "chip_light_k": 4.55,
    "chip_dark": "#d96779",
    "chip_dark_k": 4.56,
    "k_weiss": 3.03,
    "k_dunkel": 5.62
   },
   {
    "key": "Competition",
    "label": "Competition",
    "fill": "#de7d3a",
    "chip_light": "#af5400",
    "chip_light_k": 4.55,
    "chip_dark": "#d2722d",
    "chip_dark_k": 4.57,
    "k_weiss": 2.96,
    "k_dunkel": 5.75
   },
   {
    "key": "Editorial",
    "label": "Editorial",
    "fill": "#00b1a4",
    "chip_light": "#007b72",
    "chip_light_k": 4.58,
    "chip_dark": "#009d91",
    "chip_dark_k": 4.61,
    "k_weiss": 2.68,
    "k_dunkel": 6.33
   },
   {
    "key": "UGC / Community",
    "label": "UGC / Community",
    "fill": "#00a7e0",
    "chip_light": "#00769f",
    "chip_light_k": 4.52,
    "chip_dark": "#0095c9",
    "chip_dark_k": 4.54,
    "k_weiss": 2.76,
    "k_dunkel": 6.16
   },
   {
    "key": "Institutional",
    "label": "Institutional",
    "fill": "#5d9af2",
    "chip_light": "#326dc1",
    "chip_light_k": 4.59,
    "chip_dark": "#508ce3",
    "chip_dark_k": 4.58,
    "k_weiss": 2.85,
    "k_dunkel": 5.97
   },
   {
    "key": "Knowledge-Base",
    "label": "Knowledge-Base",
    "fill": "#8b8df1",
    "chip_light": "#6564c3",
    "chip_light_k": 4.5,
    "chip_dark": "#7f81e3",
    "chip_dark_k": 4.55,
    "k_weiss": 2.93,
    "k_dunkel": 5.81
   },
   {
    "key": "Brand Platforms",
    "label": "Brand Platforms",
    "fill": "#c379cf",
    "chip_light": "#9952a5",
    "chip_light_k": 4.56,
    "chip_dark": "#b970c5",
    "chip_dark_k": 4.57,
    "k_weiss": 3.02,
    "k_dunkel": 5.63
   }
  ],
  "url": [
   {
    "key": "homepage",
    "label": "Homepage",
    "familie": "Competition",
    "fill": "#e37750",
    "chip_light": "#b54d26",
    "chip_light_k": 4.61,
    "chip_dark": "#d76c45",
    "chip_dark_k": 4.52,
    "k_weiss": 2.99,
    "k_dunkel": 5.68
   },
   {
    "key": "product_service",
    "label": "Product / Service",
    "familie": "Competition",
    "fill": "#d5851b",
    "chip_light": "#9f5f00",
    "chip_light_k": 4.54,
    "chip_dark": "#c77900",
    "chip_dark_k": 4.56,
    "k_weiss": 2.92,
    "k_dunkel": 5.83
   },
   {
    "key": "marketplace",
    "label": "Marketplace",
    "familie": "Competition",
    "fill": "#b99600",
    "chip_light": "#866c00",
    "chip_light_k": 4.5,
    "chip_dark": "#a78700",
    "chip_dark_k": 4.52,
    "k_weiss": 2.83,
    "k_dunkel": 6.01
   },
   {
    "key": "company_info",
    "label": "Company Info",
    "familie": "Competition",
    "fill": "#92a52a",
    "chip_light": "#677600",
    "chip_light_k": 4.52,
    "chip_dark": "#82940b",
    "chip_dark_k": 4.58,
    "k_weiss": 2.75,
    "k_dunkel": 6.18
   },
   {
    "key": "article",
    "label": "Article",
    "familie": "Editorial",
    "fill": "#5ab15e",
    "chip_light": "#247f2d",
    "chip_light_k": 4.56,
    "chip_dark": "#459c4a",
    "chip_dark_k": 4.51,
    "k_weiss": 2.66,
    "k_dunkel": 6.38
   },
   {
    "key": "listicle",
    "label": "Listicle",
    "familie": "UGC / Community",
    "fill": "#00b48e",
    "chip_light": "#007d62",
    "chip_light_k": 4.53,
    "chip_dark": "#009d7c",
    "chip_dark_k": 4.52,
    "k_weiss": 2.65,
    "k_dunkel": 6.41
   },
   {
    "key": "guide",
    "label": "Guide",
    "familie": "Institutional",
    "fill": "#00afb2",
    "chip_light": "#007a7c",
    "chip_light_k": 4.56,
    "chip_dark": "#009b9e",
    "chip_dark_k": 4.57,
    "k_weiss": 2.7,
    "k_dunkel": 6.29
   },
   {
    "key": "comparison",
    "label": "Comparison",
    "familie": "Knowledge-Base",
    "fill": "#00aad3",
    "chip_light": "#007895",
    "chip_light_k": 4.52,
    "chip_dark": "#0098bd",
    "chip_dark_k": 4.6,
    "k_weiss": 2.73,
    "k_dunkel": 6.23
   },
   {
    "key": "review",
    "label": "Review",
    "familie": "Knowledge-Base",
    "fill": "#489fef",
    "chip_light": "#0970bc",
    "chip_light_k": 4.61,
    "chip_dark": "#378fde",
    "chip_dark_k": 4.54,
    "k_weiss": 2.81,
    "k_dunkel": 6.06
   },
   {
    "key": "documentation",
    "label": "Documentation",
    "familie": "Knowledge-Base",
    "fill": "#8190f2",
    "chip_light": "#5a65c3",
    "chip_light_k": 4.61,
    "chip_dark": "#7684e5",
    "chip_dark_k": 4.58,
    "k_weiss": 2.91,
    "k_dunkel": 5.83
   },
   {
    "key": "video",
    "label": "Video",
    "familie": "Knowledge-Base",
    "fill": "#aa82e4",
    "chip_light": "#835bb9",
    "chip_light_k": 4.51,
    "chip_dark": "#9f77d8",
    "chip_dark_k": 4.51,
    "k_weiss": 2.99,
    "k_dunkel": 5.69
   },
   {
    "key": "social_post",
    "label": "Social Post",
    "familie": "Knowledge-Base",
    "fill": "#c977c7",
    "chip_light": "#9f509d",
    "chip_light_k": 4.56,
    "chip_dark": "#bf6ebd",
    "chip_dark_k": 4.57,
    "k_weiss": 3.02,
    "k_dunkel": 5.62
   },
   {
    "key": "forum",
    "label": "Forum",
    "familie": "Brand Platforms",
    "fill": "#dd70a0",
    "chip_light": "#b14879",
    "chip_light_k": 4.58,
    "chip_dark": "#d36797",
    "chip_dark_k": 4.55,
    "k_weiss": 3.04,
    "k_dunkel": 5.59
   },
   {
    "key": "directory",
    "label": "Directory",
    "familie": "Brand Platforms",
    "fill": "#e57174",
    "chip_light": "#b8494f",
    "chip_light_k": 4.53,
    "chip_dark": "#db686b",
    "chip_dark_k": 4.59,
    "k_weiss": 3.02,
    "k_dunkel": 5.62
   }
  ],
  "mass": {
   "L_min": 0.684,
   "L_max": 0.686,
   "L_spanne": 0.002,
   "C_min": 0.116,
   "C_max": 0.146,
   "C_spanne": 0.029,
   "hue_min_abstand": 20.2,
   "doppelte_farben": false
  }
 },
 {
  "key": "familien",
  "titel": "B -- Familien",
  "satz": "Der Farbton sagt die Familie, die Helligkeit sagt das Mitglied.",
  "warum": "Jeder URL-Typ traegt genau den Farbton seines Citation-Typs. Man sieht die Zuordnung, ohne sie zu kennen -- und innerhalb der Familie unterscheidet die Helligkeit.",
  "preis": "Innerhalb einer Familie sind die Mitglieder nicht gleich schwer. Bei fuenf Mitgliedern (Knowledge-Base) reicht die Leiter von sehr dunkel bis sehr hell.",
  "cite": [
   {
    "key": "You",
    "label": "You",
    "fill": "#e47082",
    "chip_light": "#b7485c",
    "chip_light_k": 4.55,
    "chip_dark": "#d96779",
    "chip_dark_k": 4.56,
    "k_weiss": 3.03,
    "k_dunkel": 5.62
   },
   {
    "key": "Competition",
    "label": "Competition",
    "fill": "#de7d3a",
    "chip_light": "#af5400",
    "chip_light_k": 4.55,
    "chip_dark": "#d2722d",
    "chip_dark_k": 4.57,
    "k_weiss": 2.96,
    "k_dunkel": 5.75
   },
   {
    "key": "Editorial",
    "label": "Editorial",
    "fill": "#00b1a4",
    "chip_light": "#007b72",
    "chip_light_k": 4.58,
    "chip_dark": "#009d91",
    "chip_dark_k": 4.61,
    "k_weiss": 2.68,
    "k_dunkel": 6.33
   },
   {
    "key": "UGC / Community",
    "label": "UGC / Community",
    "fill": "#00a7e0",
    "chip_light": "#00769f",
    "chip_light_k": 4.52,
    "chip_dark": "#0095c9",
    "chip_dark_k": 4.54,
    "k_weiss": 2.76,
    "k_dunkel": 6.16
   },
   {
    "key": "Institutional",
    "label": "Institutional",
    "fill": "#5d9af2",
    "chip_light": "#326dc1",
    "chip_light_k": 4.59,
    "chip_dark": "#508ce3",
    "chip_dark_k": 4.58,
    "k_weiss": 2.85,
    "k_dunkel": 5.97
   },
   {
    "key": "Knowledge-Base",
    "label": "Knowledge-Base",
    "fill": "#8b8df1",
    "chip_light": "#6564c3",
    "chip_light_k": 4.5,
    "chip_dark": "#7f81e3",
    "chip_dark_k": 4.55,
    "k_weiss": 2.93,
    "k_dunkel": 5.81
   },
   {
    "key": "Brand Platforms",
    "label": "Brand Platforms",
    "fill": "#c379cf",
    "chip_light": "#9952a5",
    "chip_light_k": 4.56,
    "chip_dark": "#b970c5",
    "chip_dark_k": 4.57,
    "k_weiss": 3.02,
    "k_dunkel": 5.63
   }
  ],
  "url": [
   {
    "key": "homepage",
    "label": "Homepage",
    "familie": "Competition",
    "fill": "#ba6932",
    "chip_light": "#a5561c",
    "chip_light_k": 4.61,
    "chip_dark": "#c87640",
    "chip_dark_k": 4.52,
    "k_weiss": 4.07,
    "k_dunkel": 4.17
   },
   {
    "key": "product_service",
    "label": "Product / Service",
    "familie": "Competition",
    "fill": "#d27637",
    "chip_light": "#ae5509",
    "chip_light_k": 4.52,
    "chip_dark": "#cf7434",
    "chip_dark_k": 4.58,
    "k_weiss": 3.29,
    "k_dunkel": 5.17
   },
   {
    "key": "marketplace",
    "label": "Marketplace",
    "familie": "Competition",
    "fill": "#e58749",
    "chip_light": "#ae5508",
    "chip_light_k": 4.61,
    "chip_dark": "#d07434",
    "chip_dark_k": 4.6,
    "k_weiss": 2.66,
    "k_dunkel": 6.39
   },
   {
    "key": "company_info",
    "label": "Company Info",
    "familie": "Competition",
    "fill": "#f29c66",
    "chip_light": "#aa5b22",
    "chip_light_k": 4.55,
    "chip_dark": "#c87640",
    "chip_dark_k": 4.52,
    "k_weiss": 2.16,
    "k_dunkel": 7.87
   },
   {
    "key": "article",
    "label": "Article",
    "familie": "Editorial",
    "fill": "#00b1a4",
    "chip_light": "#007b72",
    "chip_light_k": 4.58,
    "chip_dark": "#009d91",
    "chip_dark_k": 4.61,
    "k_weiss": 2.68,
    "k_dunkel": 6.33
   },
   {
    "key": "listicle",
    "label": "Listicle",
    "familie": "UGC / Community",
    "fill": "#00a7e0",
    "chip_light": "#00769f",
    "chip_light_k": 4.52,
    "chip_dark": "#0095c9",
    "chip_dark_k": 4.54,
    "k_weiss": 2.76,
    "k_dunkel": 6.16
   },
   {
    "key": "guide",
    "label": "Guide",
    "familie": "Institutional",
    "fill": "#5d9af2",
    "chip_light": "#326dc1",
    "chip_light_k": 4.59,
    "chip_dark": "#508ce3",
    "chip_dark_k": 4.58,
    "k_weiss": 2.85,
    "k_dunkel": 5.97
   },
   {
    "key": "comparison",
    "label": "Comparison",
    "familie": "Knowledge-Base",
    "fill": "#6d6fbc",
    "chip_light": "#6365b1",
    "chip_light_k": 4.51,
    "chip_dark": "#8083d2",
    "chip_dark_k": 4.51,
    "k_weiss": 4.52,
    "k_dunkel": 3.76
   },
   {
    "key": "review",
    "label": "Review",
    "familie": "Knowledge-Base",
    "fill": "#7c7ed6",
    "chip_light": "#6464ba",
    "chip_light_k": 4.54,
    "chip_dark": "#8083db",
    "chip_dark_k": 4.57,
    "k_weiss": 3.61,
    "k_dunkel": 4.71
   },
   {
    "key": "documentation",
    "label": "Documentation",
    "familie": "Knowledge-Base",
    "fill": "#8b8df1",
    "chip_light": "#6564c3",
    "chip_light_k": 4.5,
    "chip_dark": "#7f81e3",
    "chip_dark_k": 4.55,
    "k_weiss": 2.93,
    "k_dunkel": 5.81
   },
   {
    "key": "video",
    "label": "Video",
    "familie": "Knowledge-Base",
    "fill": "#9da0fb",
    "chip_light": "#6767bd",
    "chip_light_k": 4.51,
    "chip_dark": "#8182db",
    "chip_dark_k": 4.55,
    "k_weiss": 2.37,
    "k_dunkel": 7.17
   },
   {
    "key": "social_post",
    "label": "Social Post",
    "familie": "Knowledge-Base",
    "fill": "#b0b4ff",
    "chip_light": "#696aaf",
    "chip_light_k": 4.57,
    "chip_dark": "#8184cb",
    "chip_dark_k": 4.51,
    "k_weiss": 1.94,
    "k_dunkel": 8.76
   },
   {
    "key": "forum",
    "label": "Forum",
    "familie": "Brand Platforms",
    "fill": "#b873c3",
    "chip_light": "#9754a2",
    "chip_light_k": 4.51,
    "chip_dark": "#b571c0",
    "chip_dark_k": 4.5,
    "k_weiss": 3.34,
    "k_dunkel": 5.08
   },
   {
    "key": "directory",
    "label": "Directory",
    "familie": "Brand Platforms",
    "fill": "#ca83d5",
    "chip_light": "#9955a4",
    "chip_light_k": 4.5,
    "chip_dark": "#b872c2",
    "chip_dark_k": 4.6,
    "k_weiss": 2.72,
    "k_dunkel": 6.25
   }
  ],
  "mass": {
   "L_min": 0.575,
   "L_max": 0.795,
   "L_spanne": 0.22,
   "C_min": 0.106,
   "C_max": 0.146,
   "C_spanne": 0.039,
   "hue_min_abstand": 0.0,
   "doppelte_farben": false
  }
 },
 {
  "key": "rampe",
  "titel": "C -- Linear pur",
  "satz": "Die sieben Farben der Linien-Skala, Wert fuer Wert -- und die URL-Typen als 14 Schritte auf derselben Rampe.",
  "warum": "Groesste Naehe zu den Linecharts: es IST deren Palette. Eine Farbwelt fuer die ganze App.",
  "preis": "Eine Rampe ist kein Rad: zwischen Orange und Blau liegt kein Violett und kein Magenta. You und Brand Platforms verlieren ihr Pink, die Palette wird insgesamt waermer.",
  "cite": [
   {
    "key": "You",
    "label": "You",
    "fill": "#d88225",
    "chip_light": "#a35c00",
    "chip_light_k": 4.56,
    "chip_dark": "#cb760f",
    "chip_dark_k": 4.54,
    "k_weiss": 2.94,
    "k_dunkel": 5.78
   },
   {
    "key": "Competition",
    "label": "Competition",
    "fill": "#b69700",
    "chip_light": "#846d00",
    "chip_light_k": 4.51,
    "chip_dark": "#a48800",
    "chip_dark_k": 4.51,
    "k_weiss": 2.83,
    "k_dunkel": 6.0
   },
   {
    "key": "Editorial",
    "label": "Editorial",
    "fill": "#83a93a",
    "chip_light": "#587900",
    "chip_light_k": 4.56,
    "chip_dark": "#729623",
    "chip_dark_k": 4.51,
    "k_weiss": 2.73,
    "k_dunkel": 6.23
   },
   {
    "key": "UGC / Community",
    "label": "UGC / Community",
    "fill": "#2db477",
    "chip_light": "#007f4f",
    "chip_light_k": 4.53,
    "chip_dark": "#009f64",
    "chip_dark_k": 4.54,
    "k_weiss": 2.66,
    "k_dunkel": 6.4
   },
   {
    "key": "Institutional",
    "label": "Institutional",
    "fill": "#00b1ab",
    "chip_light": "#007b76",
    "chip_light_k": 4.56,
    "chip_dark": "#009c97",
    "chip_dark_k": 4.58,
    "k_weiss": 2.67,
    "k_dunkel": 6.38
   },
   {
    "key": "Knowledge-Base",
    "label": "Knowledge-Base",
    "fill": "#00aad3",
    "chip_light": "#007895",
    "chip_light_k": 4.52,
    "chip_dark": "#0098bd",
    "chip_dark_k": 4.6,
    "k_weiss": 2.73,
    "k_dunkel": 6.23
   },
   {
    "key": "Brand Platforms",
    "label": "Brand Platforms",
    "fill": "#579cf1",
    "chip_light": "#296fc0",
    "chip_light_k": 4.55,
    "chip_dark": "#478ce0",
    "chip_dark_k": 4.51,
    "k_weiss": 2.83,
    "k_dunkel": 6.02
   }
  ],
  "url": [
   {
    "key": "homepage",
    "label": "Homepage",
    "familie": "Competition",
    "fill": "#d88225",
    "chip_light": "#a35c00",
    "chip_light_k": 4.56,
    "chip_dark": "#cb760f",
    "chip_dark_k": 4.54,
    "k_weiss": 2.94,
    "k_dunkel": 5.78
   },
   {
    "key": "product_service",
    "label": "Product / Service",
    "familie": "Competition",
    "fill": "#cb8c00",
    "chip_light": "#936400",
    "chip_light_k": 4.6,
    "chip_dark": "#b97f00",
    "chip_dark_k": 4.51,
    "k_weiss": 2.88,
    "k_dunkel": 5.9
   },
   {
    "key": "marketplace",
    "label": "Marketplace",
    "familie": "Competition",
    "fill": "#b99600",
    "chip_light": "#866c00",
    "chip_light_k": 4.5,
    "chip_dark": "#a78700",
    "chip_dark_k": 4.52,
    "k_weiss": 2.83,
    "k_dunkel": 6.01
   },
   {
    "key": "company_info",
    "label": "Company Info",
    "familie": "Competition",
    "fill": "#a59f08",
    "chip_light": "#757100",
    "chip_light_k": 4.55,
    "chip_dark": "#938e00",
    "chip_dark_k": 4.52,
    "k_weiss": 2.78,
    "k_dunkel": 6.12
   },
   {
    "key": "article",
    "label": "Article",
    "familie": "Editorial",
    "fill": "#8ca730",
    "chip_light": "#617600",
    "chip_light_k": 4.59,
    "chip_dark": "#7c9616",
    "chip_dark_k": 4.61,
    "k_weiss": 2.73,
    "k_dunkel": 6.22
   },
   {
    "key": "listicle",
    "label": "Listicle",
    "familie": "UGC / Community",
    "fill": "#6eae4e",
    "chip_light": "#3e7c16",
    "chip_light_k": 4.61,
    "chip_dark": "#5c9b3b",
    "chip_dark_k": 4.59,
    "k_weiss": 2.68,
    "k_dunkel": 6.34
   },
   {
    "key": "guide",
    "label": "Guide",
    "familie": "Institutional",
    "fill": "#48b36a",
    "chip_light": "#00803d",
    "chip_light_k": 4.54,
    "chip_dark": "#2f9e56",
    "chip_dark_k": 4.54,
    "k_weiss": 2.65,
    "k_dunkel": 6.42
   },
   {
    "key": "comparison",
    "label": "Comparison",
    "familie": "Knowledge-Base",
    "fill": "#00b585",
    "chip_light": "#007e5b",
    "chip_light_k": 4.5,
    "chip_dark": "#009e74",
    "chip_dark_k": 4.54,
    "k_weiss": 2.64,
    "k_dunkel": 6.43
   },
   {
    "key": "review",
    "label": "Review",
    "familie": "Knowledge-Base",
    "fill": "#00b29e",
    "chip_light": "#007c6d",
    "chip_light_k": 4.54,
    "chip_dark": "#009c8a",
    "chip_dark_k": 4.53,
    "k_weiss": 2.67,
    "k_dunkel": 6.36
   },
   {
    "key": "documentation",
    "label": "Documentation",
    "familie": "Knowledge-Base",
    "fill": "#00b0b1",
    "chip_light": "#007a7b",
    "chip_light_k": 4.59,
    "chip_dark": "#009b9c",
    "chip_dark_k": 4.56,
    "k_weiss": 2.68,
    "k_dunkel": 6.35
   },
   {
    "key": "video",
    "label": "Video",
    "familie": "Knowledge-Base",
    "fill": "#00adc3",
    "chip_light": "#007888",
    "chip_light_k": 4.6,
    "chip_dark": "#0099ac",
    "chip_dark_k": 4.55,
    "k_weiss": 2.7,
    "k_dunkel": 6.29
   },
   {
    "key": "social_post",
    "label": "Social Post",
    "familie": "Knowledge-Base",
    "fill": "#00a9d6",
    "chip_light": "#007798",
    "chip_light_k": 4.55,
    "chip_dark": "#0096be",
    "chip_dark_k": 4.51,
    "k_weiss": 2.75,
    "k_dunkel": 6.19
   },
   {
    "key": "forum",
    "label": "Forum",
    "familie": "Brand Platforms",
    "fill": "#29a4ea",
    "chip_light": "#0075ad",
    "chip_light_k": 4.5,
    "chip_dark": "#0092d7",
    "chip_dark_k": 4.5,
    "k_weiss": 2.77,
    "k_dunkel": 6.15
   },
   {
    "key": "directory",
    "label": "Directory",
    "familie": "Brand Platforms",
    "fill": "#579cf1",
    "chip_light": "#296fc0",
    "chip_light_k": 4.55,
    "chip_dark": "#478ce0",
    "chip_dark_k": 4.51,
    "k_weiss": 2.83,
    "k_dunkel": 6.02
   }
  ],
  "mass": {
   "L_min": 0.684,
   "L_max": 0.686,
   "L_spanne": 0.002,
   "C_min": 0.117,
   "C_max": 0.145,
   "C_spanne": 0.028,
   "hue_min_abstand": 14.5,
   "doppelte_farben": false
  }
 }
];
